import { test, expect } from '@playwright/test';
import { readdir, readFile } from 'node:fs/promises';
test('verified account, custom routine, logging, scenario comparison and responsive layout', async ({ page }, info) => {
  const email = `synthetic-${Date.now()}-${info.project.name}@example.test`;
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'Create an account', exact: true }).click();
  await page.getByLabel('Display name').fill('Test Reader');
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: false }).fill('synthetic-testing-passphrase-2026');
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.getByText('Check your email to verify your account, then sign in.')).toBeVisible();
  let verification = '';
  await expect.poll(async () => {
    for (const filename of await readdir('.local/mail')) { const message = JSON.parse(await readFile(`.local/mail/${filename}`, 'utf8')); if (message.to === email) verification = message.url; }
    return !!verification;
  }).toBe(true);
  await page.goto(verification);
  await expect(page.getByRole('heading', { name: 'Today', exact: true })).toBeVisible();
  await page.getByLabel('Your time zone').fill('Europe/Amsterdam');
  await page.getByRole('button', { name: 'Save preferences', exact: true }).click();
  await page.getByRole('button', { name: 'Plan', exact: true }).click();
  await page.getByRole('button', { name: 'New routine' }).click();
  await page.getByLabel('Routine name').fill('Synthetic routine');
  await page.getByRole('button', { name: 'Create routine', exact: true }).click();
  await page.getByRole('button', { name: 'Add an item', exact: true }).click();
  await page.getByLabel('Item name').fill('Synthetic supplement');
  await page.getByLabel('Amount per administration (mg)').fill('10');
  await page.getByRole('button', { name: 'Save item', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Synthetic supplement' })).toBeVisible();
  await page.getByRole('button', { name: 'Activate routine' }).click();
  await expect(page.getByText('Active routine', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Today', exact: true }).click();
  await page.getByRole('button', { name: 'Log an entry', exact: true }).click();
  await page.getByRole('button', { name: 'Save administration' }).click();
  await expect(page.getByText('All changes saved')).toBeVisible();
  await page.getByRole('button', { name: 'History', exact: true }).click();
  await expect(page.getByText('10 mg · taken')).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Today', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Plotter', exact: true }).click();
  await page.getByRole('button', { name: 'Add scenario', exact: true }).click();
  await page.getByLabel('Scenario name').fill('Synthetic comparison A');
  await page.getByLabel('Amount per administration (mg)').fill('10');
  await page.getByLabel('Fixed normalization reference dose (mg)').fill('10');
  await page.getByRole('button', { name: 'Plot scenario', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Within the selected interval' })).toBeVisible();
  await page.getByRole('button', { name: 'Duplicate Synthetic comparison A', exact: true }).click();
  await expect(page.getByRole('cell', { name: 'Synthetic comparison A copy' })).toBeVisible();
  await expect(page.getByText('Scenario edits do not change your routine.')).toBeVisible();
  await page.screenshot({ path: `.local/plotter-${info.project.name}.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  expect(errors).toEqual([]);
});
