import { lazy, Suspense, useCallback, useEffect, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, CalendarDays, ChartNoAxesCombined, Check, CheckCircle2, ChevronRight, Circle, Clock3, Copy, Download, Heart, History, LogOut, Plus, RotateCcw, Settings, Sparkles, WifiOff } from 'lucide-react';
import { Temporal } from '@js-temporal/polyfill';
import { administrationSchema, convert, emptyProtocol, occurrences, phaseSchema, preferencesSchema, supplies, type Entry, type Occurrence, type Operation, type Phase } from '../../../packages/domain/src/index.js';
import { catalog } from '../../../packages/domain/src/catalog.js';
import { api, post, local, readCached, enqueue, synchronize, download, type Workspace, type SavedRecord } from './api.js';
import { Empty, Field, Sheet, formatDate, formatTime } from './ui.js';
import { EntryEditor } from './EntryEditor.js';
import { HealthEditor } from './HealthEditor.js';
import { ImportPanel } from './ImportPanel.js';
const Plotter = lazy(() => import('./Plotter.js'));
const newId = () => crypto.randomUUID();
type User = { id: string; name: string; email: string };
const tabs = [{ id: 'today', label: 'Today', icon: CalendarDays }, { id: 'plan', label: 'Plan', icon: Circle }, { id: 'plotter', label: 'Plotter', icon: ChartNoAxesCombined }, { id: 'history', label: 'History', icon: History }, { id: 'health', label: 'Health', icon: Heart }];

function Auth({ onSignedIn }: { onSignedIn(u: User): void }) {
  const [mode, setMode] = useState<'sign-in' | 'sign-up' | 'recovery'>('sign-in'); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const config = useQuery({ queryKey: ['config'], queryFn: () => api('/api/config') });
  const token = new URLSearchParams(location.search).get('token');
  return <main className="auth-layout"><section className="auth-card"><div className="brand"><Activity/> CycleTracker</div><h1>{token ? 'New password' : mode === 'sign-up' ? 'Create account' : mode === 'recovery' ? 'Reset password' : 'Sign in'}</h1>
    <form onSubmit={async e => { e.preventDefault(); setError(''); setMessage(''); setBusy(true); const values = Object.fromEntries(new FormData(e.currentTarget)); try {
      if (token) { await post('/api/auth/reset-password', { token, newPassword: values.password }); history.replaceState(null, '', '/'); setMessage('Password updated. Sign in to continue.'); }
      else if (mode === 'recovery') { await post('/api/auth/request-password-reset', { email: values.email, redirectTo: location.origin }); setMessage('If the account exists, a recovery email is on its way.'); }
      else if (mode === 'sign-up') { await post('/api/auth/sign-up/email', { ...values, callbackURL: location.origin }); setMessage('Check your email to verify your account, then sign in.'); }
      else { const result = await post('/api/auth/sign-in/email', values); onSignedIn(result.user); }
    } catch (err: any) { setError(err.message); } finally { setBusy(false); } }}>
      {mode === 'sign-up' && <Field label="Display name"><input name="name" autoComplete="name" required/></Field>}
      {!token && <Field label="Email address"><input name="email" type="email" autoComplete="email" required/></Field>}
      {(token || mode !== 'recovery') && <Field label="Password"><input name="password" type="password" minLength={12} autoComplete={mode === 'sign-up' || token ? 'new-password' : 'current-password'} required/><small>At least 12 characters</small></Field>}
      {error && <p className="error" role="alert">{error}</p>}{message && <div className="notice" role="status">{message}</div>}
      <button className="primary full" disabled={busy}>{busy ? 'One moment…' : token ? 'Update password' : mode === 'sign-up' ? 'Create account' : mode === 'recovery' ? 'Send recovery email' : 'Sign in'}<ChevronRight size={16}/></button>
    </form><div className="row wrap auth-actions"><button className="text-button" onClick={() => { setMode(mode === 'sign-up' ? 'sign-in' : 'sign-up'); setError(''); setMessage(''); }}>{mode === 'sign-up' ? 'Already have an account? Sign in' : 'Create an account'}</button><button className="text-button" onClick={() => setMode('recovery')}>Forgot password?</button></div>
    {(config.data?.google || config.data?.apple) && <div className="row">{['google', 'apple'].filter(p => config.data[p]).map(provider => <button key={provider} onClick={async () => { try { const result = await post('/api/auth/sign-in/social', { provider, callbackURL: location.origin }); if (result.url) location.assign(result.url); } catch (e: any) { setError(e.message); } }}>Continue with {provider}</button>)}</div>}
    {config.data?.developmentMail && <p className="development-note">Local development: verification and recovery emails are saved in .local/mail.</p>}
  </section></main>;
}

export default function App() {
  const [user, setUser] = useState<User | null>(null); const [ready, setReady] = useState(false);
  useEffect(() => { api('/api/auth/get-session').then(s => { setUser(s?.user ?? null); if (s?.user) localStorage.setItem('cycletracker-active-user', JSON.stringify(s.user)); }).catch(() => { if (!navigator.onLine) { const previous = localStorage.getItem('cycletracker-active-user'); if (previous) setUser(JSON.parse(previous)); } }).finally(() => setReady(true)); }, []);
  if (!ready) return <div className="loading">Opening your workspace…</div>;
  if (!user) return <Auth onSignedIn={u => { localStorage.setItem('cycletracker-active-user', JSON.stringify(u)); setUser(u); }}/>;
  return <WorkspaceApp user={user} onSignOut={() => setUser(null)}/>;
}

function WorkspaceApp({ user, onSignOut }: { user: User; onSignOut(): void }) {
  const client = useQueryClient(); const [tab, setTab] = useState('today'); const [settings, setSettings] = useState(false); const [error, setError] = useState(''); const [toast, setToast] = useState(''); const [pending, setPending] = useState(0); const [online, setOnline] = useState(navigator.onLine); const [optimistic, setOptimistic] = useState<SavedRecord[]>([]);
  const workspace = useQuery({ queryKey: ['workspace', user.id], queryFn: () => readCached<Workspace>(user.id, 'workspace', () => api('/workspace')) });
  const records = useQuery({ queryKey: ['records', user.id], queryFn: () => readCached<{ items: SavedRecord[]; nextCursor: string | null }>(user.id, 'records', () => api('/records?limit=100')) });
  const ws = workspace.data;
  const reload = useCallback(async () => { await client.invalidateQueries({ queryKey: ['records', user.id] }); await client.invalidateQueries({ queryKey: ['workspace', user.id] }); }, [client, user.id]);
  const sync = useCallback(async () => { try { await synchronize(user.id); setOptimistic([]); await reload(); } catch (e: any) { setError(e.message); } setPending(await local.queue.where('owner').equals(user.id).count()); }, [user.id, reload]);
  useEffect(() => { const update = () => { setOnline(navigator.onLine); if (navigator.onLine) void sync(); }; window.addEventListener('online', update); window.addEventListener('offline', update); void local.queue.where('owner').equals(user.id).toArray().then(q => { setPending(q.length); setOptimistic(q.map(x => ({ id: x.operation.id, kind: x.operation.kind, data: x.operation.data, version: x.operation.expectedVersion + 1, eventAt: (x.operation.data as any).at ?? new Date().toISOString(), pending: true }))); if (navigator.onLine) void sync(); }); return () => { window.removeEventListener('online', update); window.removeEventListener('offline', update); }; }, [sync, user.id]);
  useEffect(() => { const theme = ws?.preferences.theme ?? 'system'; const mq = matchMedia('(prefers-color-scheme: dark)'); const apply = () => document.documentElement.dataset.theme = theme === 'system' ? (mq.matches ? 'dark' : 'light') : theme; apply(); mq.addEventListener('change', apply); return () => mq.removeEventListener('change', apply); }, [ws?.preferences.theme]);
  const saveRecord = async (kind: Operation['kind'], data: any, existing?: SavedRecord) => {
    const operation: Operation = { id: existing?.id ?? newId(), operationId: newId(), kind, expectedVersion: existing?.version ?? 0, data };
    await enqueue(user.id, operation); const row: SavedRecord = { id: operation.id, kind, data, version: operation.expectedVersion + 1, eventAt: data.at ?? new Date().toISOString(), pending: true };
    setOptimistic(old => [row, ...old.filter(x => x.id !== row.id)]); setPending(await local.queue.where('owner').equals(user.id).count()); setToast(navigator.onLine ? 'Saved locally. Syncing…' : 'Saved locally. Will sync when connected.'); void sync(); return row;
  };
  const saveWorkspace = async (patch: Partial<Workspace>) => { const next = await post<Workspace>('/workspace', { ...patch, expectedVersion: ws!.version }, 'PUT'); client.setQueryData(['workspace', user.id], next); await local.cache.put({ key: `${user.id}:workspace`, owner: user.id, value: next }); };
  const allRecords = [...optimistic, ...(records.data?.items ?? []).filter(x => !optimistic.some(o => o.id === x.id))];
  const signOut = async () => {
    if (pending && !confirm('There are unsynced changes. Signing out will discard them from this device. Continue?')) return;
    try { await post('/api/auth/sign-out', {}); } catch { if (navigator.onLine) { setError('Sign-out failed. Try again.'); return; } }
    await local.cache.where('owner').equals(user.id).delete(); await local.queue.where('owner').equals(user.id).delete(); localStorage.removeItem('cycletracker-active-user'); client.clear(); onSignOut();
  };
  if (!ws) return <div className="loading">{workspace.error ? <><p>{workspace.error.message}</p><button onClick={() => void workspace.refetch()}>Retry</button><button onClick={signOut}>Sign out</button></> : 'Loading your routine…'}</div>;
  const active = ws.protocol.phases.find(p => p.id === ws.protocol.activePhaseId);
  const shared = { user, ws, records: allRecords, saveRecord, saveWorkspace, reload, setError, setToast };
  return <div className="app"><aside className="sidebar"><a className="brand" href="/"><Activity size={26}/> CycleTracker</a><nav aria-label="Main navigation">{tabs.filter(t => t.id !== 'health' || ws.preferences.healthEnabled).map(t => <button key={t.id} className={tab === t.id ? 'active' : ''} onClick={() => setTab(t.id)}><t.icon size={19}/><span>{t.label}</span>{tab === t.id && <span className="active-dot"/>}</button>)}</nav><div className="sidebar-bottom"><button className="profile" onClick={() => setSettings(true)}><span className="avatar">{user.name.slice(0, 1).toUpperCase()}</span><span>{user.name}</span><Settings size={17}/></button></div></aside>
    <div className="main-wrap"><header className="topbar"><span className="breadcrumb">Workspace <ChevronRight size={13}/> {tabs.find(t => t.id === tab)?.label}</span><div className="row"><span className="sync-status">{!online ? <><WifiOff size={14}/> Offline</> : pending ? <button className="text-button" onClick={() => void sync()}>{pending} pending · Retry sync</button> : <><span className="status-dot"/> All changes saved</>}</span><button className="icon-button mobile-settings" aria-label="Settings" onClick={() => setSettings(true)}><Settings size={20}/></button></div></header>
    <main className="main">{error && <div className="error-banner" role="alert">{error}<button className="text-button" onClick={() => setError('')}>Dismiss</button></div>}{records.error && <div className="error-banner">{records.error.message}<button onClick={() => void records.refetch()}>Retry history</button></div>}
      {!ws.preferences.onboardingComplete && <Onboarding ws={ws} save={saveWorkspace}/>}
      {tab === 'today' && <Today {...shared} active={active} goPlan={() => setTab('plan')}/>}
      {tab === 'plan' && <Plan {...shared}/>}
      {tab === 'plotter' && <Suspense fallback={<div className="loading">Loading Plotter…</div>}><Plotter {...shared}/></Suspense>}
      {tab === 'history' && <HistoryView {...shared} firstCursor={records.data?.nextCursor ?? null}/>}
      {tab === 'health' && <Health {...shared}/>}
    </main></div>
    {toast && <div className="toast" role="status"><CheckCircle2 size={18}/>{toast}<button className="text-button" onClick={() => setToast('')}>Dismiss</button></div>}
    <Sheet open={settings} onClose={() => setSettings(false)} title="Your workspace" description="Preferences, account access and your data."><SettingsPanel {...shared} signOut={signOut}/></Sheet>
  </div>;
}
export type Shared = { user: User; ws: Workspace; records: SavedRecord[]; saveRecord(kind: Operation['kind'], data: any, existing?: SavedRecord): Promise<SavedRecord>; saveWorkspace(patch: Partial<Workspace>): Promise<void>; reload(): Promise<void>; setError(e: string): void; setToast(t: string): void };
function Onboarding({ ws, save }: { ws: Workspace; save(p: Partial<Workspace>): Promise<void> }) {
  const [zone, setZone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone); const [error, setError] = useState('');
  return <section className="onboarding"><div><h3>Set your time zone</h3><p>Used for new schedules. Existing schedules keep their own time zone.</p></div><form onSubmit={async e => { e.preventDefault(); try { Temporal.Now.zonedDateTimeISO(zone); await save({ preferences: { ...ws.preferences, timeZone: zone, locale: navigator.language, onboardingComplete: true } }); } catch (err: any) { setError(err.message); } }}><Field label="Your time zone"><input value={zone} onChange={e => setZone(e.target.value)}/></Field><button className="primary">Save preferences</button>{error && <p className="error">{error}</p>}</form></section>;
}
function Today(props: Shared & { active?: Phase; goPlan(): void }) {
  const { active, ws, records, saveRecord, setError } = props; const [detail, setDetail] = useState<{ entry: Entry; occurrence?: Occurrence } | null>(null);
  const now = Temporal.Now.zonedDateTimeISO(ws.preferences.timeZone); const from = now.startOfDay().toInstant().toString(); const to = now.startOfDay().add({ days: 1 }).toInstant().toString();
  const activation = ws.protocol.activations.at(-1);
  const agenda = active ? occurrences(active, from, to).filter(o => !activation || Date.parse(o.at) >= Date.parse(activation.at)) : [];
  const completed = (o: Occurrence) => records.find(r => r.kind === 'administration' && r.data.occurrenceId === o.id && r.data.status !== 'retracted');
  const taken = agenda.filter(o => completed(o)?.data.status === 'taken').length;
  const record = async (o: Occurrence, status = 'taken') => { try { await saveRecord('administration', administrationSchema.parse({ occurrenceId: o.id, phaseId: o.phaseId, entryId: o.entryId, at: new Date().toISOString(), status, snapshot: o.entry, amount: o.amount })); } catch (e: any) { setError(e.message); } };
  const lastBP = records.find(r => r.kind === 'health' && r.data.values?.some((x: any) => x.name.toLowerCase() === 'systolic'));
  return <><div className="page-heading"><div><span className="eyebrow">{now.toPlainDate().toLocaleString('en-GB', { weekday: 'long', day: 'numeric', month: 'long' }).toUpperCase()}</span><h1>Today</h1></div><button className="primary" onClick={() => active?.entries[0] ? setDetail({ entry: active.entries[0] }) : props.goPlan()}><Plus size={17}/> Log an entry</button></div>
    <section className="summary-grid"><article className="summary-card"><span className="card-label">CURRENT ROUTINE <Circle size={16}/></span><strong>{active?.name ?? 'No active routine'}</strong><span className="muted">{active ? `${active.entries.filter(e => e.enabled).length} items · ${active.category}` : 'Create a routine in Plan'}</span></article><article className="summary-card"><span className="card-label">TODAY'S PROGRESS <CheckCircle2 size={16}/></span><strong>{taken}<span className="subtle"> / {agenda.length}</span></strong><div className="progress"><span style={{ width: `${agenda.length ? taken / agenda.length * 100 : 0}%` }}/></div><span className="muted">{agenda.length ? 'scheduled administrations recorded' : 'No scheduled items today'}</span></article><article className="summary-card"><span className="card-label">LATEST BLOOD PRESSURE <Heart size={16}/></span><strong>{lastBP ? lastBP.data.values.filter((x: any) => ['systolic', 'diastolic'].includes(x.name.toLowerCase())).map((x: any) => x.value).join(' / ') : '—'}<span className="unit">{lastBP ? 'mmHg' : ''}</span></strong><span className="muted">{lastBP ? formatDate(lastBP.data.at) : 'No measurement recorded'}</span></article></section>
    <div className="today-grid"><section className="panel"><div className="panel-heading"><div><h2>Today's agenda</h2><p className="muted">{ws.preferences.timeZone} · Your active routine</p></div><span className="badge">{agenda.length} scheduled</span></div>{!agenda.length ? <Empty title="No scheduled items">{active ? 'Nothing is scheduled for today. As-needed items are available below.' : <><span>Create and activate a routine to schedule items.</span><br/><button className="primary" onClick={props.goPlan}><Plus size={16}/> Create routine</button></>}</Empty> : <div className="agenda">{agenda.map(o => { const done = completed(o); return <div className={`agenda-row ${done ? 'done' : ''}`} key={o.id}><span className="time">{new Date(o.at).toLocaleTimeString([], { timeZone: ws.preferences.timeZone, hour: '2-digit', minute: '2-digit' })}</span><div className="item-icon"><Activity size={18}/></div><button className="item-description" onClick={() => setDetail({ entry: o.entry, occurrence: o })}><strong>{o.entry.name}</strong><small>{o.amount.value} {o.amount.unit} · {o.entry.route}{o.adjusted ? ' · DST adjusted' : ''}</small></button>{done ? <><span className="badge green">{done.data.status === 'taken' ? 'Taken' : 'Skipped'}</span><button className="icon-button" aria-label={`Undo ${o.entry.name}`} onClick={() => void saveRecord('administration', { ...done.data, status: 'retracted' }, done)}><RotateCcw size={16}/></button></> : <><span className="due-label">{Date.parse(o.at) < Date.now() ? 'Overdue' : 'Pending'}</span><button className="take-button" onClick={() => void record(o)}><Check size={15}/> Taken</button><button className="text-button" onClick={() => void record(o, 'skipped')}>Skip</button></>}</div>; })}</div>}</section>
    <aside className="stack"><section className="panel quiet-card"><h3>Note</h3><QuickNote {...props}/></section></aside></div>
    {active && <section className="panel routine-strip"><div><h2>Your routine</h2><p className="muted">Quick log</p></div><div className="row wrap">{active.entries.filter(e => e.enabled).map(e => <button key={e.id} onClick={() => setDetail({ entry: e })}><Plus size={15}/>{e.name}</button>)}</div></section>}
    <Sheet title="Record an administration" open={!!detail} onClose={() => setDetail(null)}>{detail && <AdministrationForm entry={detail.entry} occurrence={detail.occurrence} phaseId={active?.id} save={async data => { await saveRecord('administration', data); setDetail(null); }}/>}</Sheet>
  </>;
}
function AdministrationForm({ entry, occurrence, phaseId, existing, save }: { entry: Entry; occurrence?: Occurrence; phaseId?: string; existing?: SavedRecord; save(data: any): Promise<void> }) {
  const [amount, setAmount] = useState(existing?.data.amount.value ?? occurrence?.amount.value ?? entry.amount.value); const [error, setError] = useState('');
  const initial = new Date(existing?.data.at ?? Date.now()); const localTime = new Date(initial.getTime() - initial.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
  let volume = ''; try { if (entry.concentration) volume = `${convert({ value: amount, unit: entry.amount.unit }, 'mL', entry.concentration).toPrecision(4)} mL`; } catch { /* incompatible conversion is omitted */ }
  return <form onSubmit={async e => { e.preventDefault(); const v = Object.fromEntries(new FormData(e.currentTarget)); try { await save(administrationSchema.parse({ occurrenceId: existing?.data.occurrenceId ?? occurrence?.id ?? null, entryId: entry.id, phaseId: existing?.data.phaseId ?? phaseId ?? null, snapshot: entry, amount: { value: +amount, unit: entry.amount.unit }, status: 'taken', at: new Date(v.at as string).toISOString(), site: v.site, note: v.note })); } catch (e: any) { setError(e.message); } }}><h3>{entry.name}</h3><div className="grid two"><Field label={`Actual amount (${entry.amount.unit})`}><input type="number" step="any" min="0.000001" value={amount} onChange={e => setAmount(+e.target.value)} required/></Field><Field label="Actual time (device local)"><input type="datetime-local" name="at" defaultValue={localTime} required/></Field></div>{volume && <div className="notice">Draw volume: {volume} · {entry.concentration?.value} {entry.concentration?.unit}/mL</div>}<Field label="Injection site (optional)"><input name="site" defaultValue={existing?.data.site} placeholder="e.g. Left thigh"/></Field><Field label="Note"><textarea name="note" defaultValue={existing?.data.note}/></Field>{error && <p className="error">{error}</p>}<button className="primary full">Save administration</button></form>;
}
function QuickNote({ saveRecord }: Shared) { const [text, setText] = useState(''); return <form onSubmit={async e => { e.preventDefault(); if (!text.trim()) return; await saveRecord('health', { kind: 'note', title: 'Daily check-in', at: new Date().toISOString(), note: text, values: [] }); setText(''); }}><textarea aria-label="Private note" value={text} onChange={e => setText(e.target.value)} placeholder="Add a note…"/><button className="text-button" disabled={!text.trim()}>Save note <ChevronRight size={15}/></button></form>; }

function Plan(props: Shared) {
  const { ws, saveWorkspace, setError } = props; const [selected, setSelected] = useState(ws.protocol.activePhaseId ?? ws.protocol.phases[0]?.id); const [edit, setEdit] = useState<Entry | 'new' | null>(null); const [create, setCreate] = useState(false); const [supply, setSupply] = useState(false); const [archived, setArchived] = useState(false);
  const current = ws.protocol.phases.find(p => p.id === selected); const update = async (phase: Phase) => saveWorkspace({ protocol: { ...ws.protocol, phases: ws.protocol.phases.map(p => p.id === phase.id ? phase : p) } });
  const attempt = (fn: () => Promise<any>) => void fn().catch(e => setError(e.message));
  return <><div className="page-heading"><div><h1>Plan</h1></div><button className="primary" onClick={() => setCreate(true)}><Plus size={17}/> New routine</button></div>
    <div className="row spread wrap"><div className="pills">{ws.protocol.phases.filter(p => p.archived === archived).map(p => <button className={selected === p.id ? 'selected' : ''} key={p.id} onClick={() => setSelected(p.id)}>{p.name}{p.id === ws.protocol.activePhaseId && <span className="status-dot"/>}</button>)}</div><button className="text-button" onClick={() => setArchived(!archived)}>{archived ? 'Current & planned' : 'Archived routines'}</button></div>
    {!current ? <section className="panel"><Empty title="No routines">Create a routine to add items and schedules.</Empty></section> : <><section className="panel"><div className="panel-heading"><div><span className="badge green">{ws.protocol.activePhaseId === current.id ? 'Active routine' : current.archived ? 'Archived' : 'Draft · Not active'}</span><h2>{current.name}</h2><p className="muted">{current.category}{current.notes ? ` · ${current.notes}` : ''}</p></div><div className="row wrap"><button onClick={() => attempt(async () => { const p = structuredClone(current); p.id = newId(); p.name += ' copy'; p.archived = false; p.entries.forEach(e => { e.id = newId(); e.version = 1; }); await saveWorkspace({ protocol: { ...ws.protocol, phases: [...ws.protocol.phases, p] } }); setSelected(p.id); })}><Copy size={15}/> Duplicate</button>{ws.protocol.activePhaseId !== current.id && !current.archived && <button className="primary" onClick={() => attempt(async () => { await post('/activate', { phaseId: current.id, expectedVersion: ws.version, at: new Date().toISOString() }); await props.reload(); })}>Activate routine</button>}{ws.protocol.activePhaseId === current.id && <button onClick={() => attempt(async () => { await post('/activate', { phaseId: null, expectedVersion: ws.version, at: new Date().toISOString() }); await props.reload(); })}>Complete phase</button>}</div></div>
    {!current.entries.length ? <Empty title="No items">Add a medication, supplement or custom item.</Empty> : current.entries.map(e => <div className="plan-item" key={e.id}><div className="item-icon"><Activity size={18}/></div><div className="grow"><h3>{e.name}</h3><p>{e.schedule.kind === 'prn' ? 'As needed' : e.schedule.slots.map(s => `${s.time} · ${s.amount.value} ${s.amount.unit}`).join(' / ')}<span className="muted"> · {e.route}</span></p><small className="muted">{e.schedule.kind === 'interval' ? `Every ${e.schedule.intervalDays} calendar days` : e.schedule.kind === 'elapsed' ? `Every ${e.schedule.intervalHours} hours` : e.schedule.kind} · {e.schedule.timeZone}</small></div><button onClick={() => setEdit(e)}>Edit</button><button className="text-button" onClick={() => attempt(() => update({ ...current, entries: current.entries.map(x => x.id === e.id ? { ...x, enabled: !x.enabled } : x) }))}>{e.enabled ? 'Pause' : 'Enable'}</button></div>)}
    <div className="panel-foot"><button className="text-button" onClick={() => setEdit('new')}><Plus size={16}/> Add an item</button><button className="text-button" onClick={() => setSupply(true)}>Supply estimate <ChevronRight size={15}/></button><button className="text-button" onClick={() => window.print()}>Print plan</button></div></section>
    <section className="panel"><h3>Routine details</h3><form onSubmit={e => { e.preventDefault(); const d = Object.fromEntries(new FormData(e.currentTarget)); attempt(() => update({ ...current, name: d.name as string, category: d.category as string, notes: d.notes as string, plannedStart: d.start as string || undefined, plannedEnd: d.end as string || undefined })); }}><div className="grid two"><Field label="Name"><input name="name" key={current.id} defaultValue={current.name} required/></Field><Field label="Category"><input name="category" defaultValue={current.category}/></Field></div><div className="grid two"><Field label="Planned start (does not activate)"><input type="date" name="start" defaultValue={current.plannedStart}/></Field><Field label="Planned end"><input type="date" name="end" defaultValue={current.plannedEnd}/></Field></div><Field label="Private notes"><textarea name="notes" defaultValue={current.notes}/></Field><div className="row"><button>Save details</button>{ws.protocol.activePhaseId !== current.id && <button type="button" onClick={() => attempt(() => update({ ...current, archived: !current.archived }))}>{current.archived ? 'Restore' : 'Archive'}</button>}<button type="button" onClick={() => attempt(() => saveWorkspace({ protocol: { ...ws.protocol, phases: [current, ...ws.protocol.phases.filter(p => p.id !== current.id)] } }))}>Move to first</button></div></form></section></>}
    <Sheet open={create} onClose={() => setCreate(false)} title="Create a routine"><form onSubmit={e => { e.preventDefault(); const form = Object.fromEntries(new FormData(e.currentTarget)); attempt(async () => { const p = phaseSchema.parse({ id: newId(), name: form.name, category: form.category, entries: [] }); await saveWorkspace({ protocol: { ...ws.protocol, phases: [...ws.protocol.phases, p] } }); setSelected(p.id); setCreate(false); }); }}><Field label="Routine name"><input name="name" required placeholder="e.g. Everyday routine"/></Field><Field label="Category"><select name="category"><option>Ongoing</option><option>Temporary</option><option>Break</option><option>Custom</option></select></Field><button className="primary full">Create routine</button></form></Sheet>
    <Sheet open={!!edit} onClose={() => setEdit(null)} title={edit === 'new' ? 'Add an item' : 'Edit item'}>{edit && current && <EntryEditor key={edit === 'new' ? 'new' : edit.id} timeZone={ws.preferences.timeZone} value={edit === 'new' ? undefined : edit} onSave={async e => { await update({ ...current, entries: edit === 'new' ? [...current.entries, e] : current.entries.map(x => x.id === e.id ? e : x) }); setEdit(null); }}/>}</Sheet>
    <Sheet open={supply} onClose={() => setSupply(false)} title="Supply estimate" description="Planned consumption, separate from stock on hand.">{current && <Supply phase={current}/>}</Sheet>
    <section className="panel"><h2>Compound library</h2><p className="muted">Every formulation can be tracked. Plotting depends on the available evidence.</p><div className="catalog-grid">{catalog.map(c => <div key={c.id}><strong>{c.name}</strong><small>{c.route}</small><span className="badge">{c.capability === 'tracking-only' ? 'Tracking only' : 'Relative model'}</span></div>)}</div></section>
  </>;
}
function Supply({ phase }: { phase: Phase }) { const [days, setDays] = useState(30); let rows: ReturnType<typeof supplies> = []; let error = ''; try { rows = supplies(phase, new Date().toISOString(), new Date(Date.now() + days * 864e5).toISOString()); } catch (e: any) { error = e.message; } return <><Field label="Days ahead"><input type="number" min="1" max="1825" value={days} onChange={e => setDays(+e.target.value)}/></Field><p className="muted">Uses this phase's schedule. {phase.plannedStart ? 'Planned dates are assumptions until activation.' : 'Future phase transitions are not assumed.'}</p>{error && <p className="error">{error}</p>}{rows.map(r => <div className="list-row" key={r.entry.id}><strong>{r.entry.name}</strong><span>{r.uncertain ? 'As-needed usage is unknown' : `${r.count} administrations · ${r.quantity.toFixed(2)} ${r.unit}${r.packages === null ? ' · package not configured' : ` · ${r.packages} packages`}`}</span></div>)}</>; }

function HistoryView(props: Shared & { firstCursor: string | null }) {
  const [extra, setExtra] = useState<SavedRecord[]>([]); const [cursor, setCursor] = useState(props.firstCursor); const [filter, setFilter] = useState('all'); const [search, setSearch] = useState(''); const [edit, setEdit] = useState<SavedRecord | null>(null);
  useEffect(() => { setCursor(props.firstCursor); setExtra([]); }, [props.firstCursor]);
  const rows = [...props.records, ...extra.filter(x => !props.records.some(p => p.id === x.id))].filter(r => !['scenario', 'compound'].includes(r.kind) && !r.data.deleted && (filter === 'all' || r.kind === filter) && JSON.stringify(r.data).toLowerCase().includes(search.toLowerCase()));
  return <><div className="page-heading"><div><h1>History</h1></div></div><div className="row filters"><input aria-label="Search loaded history" placeholder="Search loaded history…" value={search} onChange={e => setSearch(e.target.value)}/><select aria-label="Record type" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All records</option><option value="administration">Administrations</option><option value="health">Health & notes</option></select></div><section className="panel">{!rows.length ? <Empty title="No records">Administrations and health entries appear here.</Empty> : rows.map(r => <div className="history-row" key={r.id}><div className="item-icon">{r.kind === 'health' ? <Heart size={18}/> : <Activity size={18}/>}</div><div className="grow"><strong>{r.data.snapshot?.name ?? r.data.title}</strong><p>{r.kind === 'administration' ? `${r.data.amount.value} ${r.data.amount.unit} · ${r.data.status}` : r.data.note || r.data.values?.map((v: any) => `${v.name}: ${v.value} ${v.unit}`).join(' · ')}</p><small className="muted">{formatDate(r.eventAt)} · {formatTime(r.eventAt)}{r.version > 1 ? ` · edited, revision ${r.version}` : ''}{r.pending ? ' · saved locally' : ''}</small></div>{r.kind === 'administration' && r.data.status !== 'retracted' && <button onClick={() => setEdit(r)}>Edit</button>}<button className="text-button" onClick={async () => { try { if (r.kind === 'administration') await props.saveRecord('administration', { ...r.data, status: 'retracted' }, r); else await props.saveRecord('health', { ...r.data, deleted: true }, r); } catch (e: any) { props.setError(e.message); } }}>{r.kind === 'administration' ? 'Retract' : 'Delete'}</button></div>)}</section>{cursor && <button className="load-more" onClick={async () => { try { const result = await api(`/records?limit=100&cursor=${encodeURIComponent(cursor)}`); setExtra(old => [...old, ...result.items]); setCursor(result.nextCursor); } catch (e: any) { props.setError(e.message); } }}>Load more history</button>}<p className="muted small">{cursor ? 'More records are available. Search applies to loaded records.' : 'All fetched records shown.'}</p><Sheet open={!!edit} onClose={() => setEdit(null)} title="Edit recorded administration">{edit && <AdministrationForm entry={edit.data.snapshot} existing={edit} save={async data => { await props.saveRecord('administration', data, edit); setEdit(null); }}/>}</Sheet></>;
}
function Health(props: Shared) {
  const [edit, setEdit] = useState<SavedRecord | 'new' | null>(null);
  const [filter, setFilter] = useState('all');
  const rows = props.records.filter(r => r.kind === 'health' && !r.data.deleted && (filter === 'all' || r.data.kind === filter));
  const markerKeys = [...new Set(rows.flatMap(r => r.data.values?.map((v: any) => `${v.name}|${v.unit}`) ?? []))] as string[];
  const [selectedMarker, setSelectedMarker] = useState('');
  const key = selectedMarker || markerKeys[0];
  const trend = rows.flatMap(r => r.data.values?.filter((v: any) => `${v.name}|${v.unit}` === key).map((v: any) => ({ at: r.data.at, value: v.value })) ?? []).sort((a, b) => a.at.localeCompare(b.at));
  const min = Math.min(...trend.map(x => x.value)), max = Math.max(...trend.map(x => x.value));
  const points = trend.map((x, i) => `${15 + i * 470 / Math.max(1, trend.length - 1)},${110 - (x.value - min) / (max - min || 1) * 90}`).join(' ');
  return <><div className="page-heading"><h1>Health</h1><button className="primary" onClick={() => setEdit('new')}><Plus size={17}/> Add observation</button></div>
    <div className="row filters"><select aria-label="Health record type" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All observations</option><option value="measurement">Measurements</option><option value="symptom">Symptoms</option><option value="lab">Lab panels</option><option value="note">Notes</option></select></div>
    {trend.length > 1 && <section className="panel"><div className="row spread"><h2>Trend</h2><select aria-label="Trend marker" style={{maxWidth:250}} value={key} onChange={e => setSelectedMarker(e.target.value)}>{markerKeys.map(k => <option key={k} value={k}>{k.replace('|', ' · ')}</option>)}</select></div><svg viewBox="0 0 500 135" role="img" aria-label={`${key}: ${trend.map(x => `${formatDate(x.at)} ${x.value}`).join(', ')}`} style={{width:'100%',height:150}}><polyline points={points} fill="none" stroke="var(--accent)" strokeWidth="2"/>{trend.map((x,i) => <circle key={i} cx={15 + i * 470 / Math.max(1, trend.length - 1)} cy={110 - (x.value-min)/(max-min||1)*90} r="3" fill="var(--accent)"><title>{formatDate(x.at)}: {x.value}</title></circle>)}</svg><p className="muted small">{formatDate(trend[0].at)} – {formatDate(trend.at(-1)!.at)} · {trend.length} loaded observations · original units</p></section>}
    <section className="panel">{!rows.length ? <Empty title="No health records">Add a measurement, symptom, note or lab panel.</Empty> : rows.map(r => <div className="health-card" key={r.id}><div className="row spread"><h3>{r.data.title}</h3><div className="row"><span className="badge">{r.data.kind}</span><button onClick={() => setEdit(r)}>Edit</button><button className="text-button" onClick={() => void props.saveRecord('health', {...r.data,deleted:true},r)}>Delete</button></div></div><span className="muted small">{formatDate(r.data.at)}{r.data.samplingTimeKnown === false ? ' · sampling time unknown' : ` · ${formatTime(r.data.at)}`}</span><div className="marker-grid">{r.data.values?.map((v: any, i: number) => <div key={i} className={(v.low != null && v.value < v.low) || (v.high != null && v.value > v.high) ? 'flagged' : ''}><span>{v.name}</span><strong>{v.value} <small>{v.unit}</small></strong>{(v.low != null || v.high != null) && <small>Lab range: {v.low ?? '—'}–{v.high ?? '—'}</small>}</div>)}</div><p>{r.data.note}</p>{r.data.documentId && <a href={`/api/v1/documents/${r.data.documentId}`}>Download original PDF</a>}</div>)}</section>
    <Sheet open={!!edit} onClose={() => setEdit(null)} title={edit === 'new' ? 'Add observation' : 'Edit observation'}>{edit && <HealthEditor key={edit === 'new' ? 'new' : edit.id} initial={edit === 'new' ? undefined : edit.data} save={async data => { await props.saveRecord('health', data, edit === 'new' ? undefined : edit); setEdit(null); }}/>}</Sheet></>;
}

function SettingsPanel(props: Shared & { signOut(): Promise<void> }) {
  const [prefs, setPrefs] = useState(props.ws.preferences); const [message, setMessage] = useState(''); const [sessions, setSessions] = useState<any[]>([]);
  return <div className="stack"><form onSubmit={async e => { e.preventDefault(); try { Temporal.Now.zonedDateTimeISO(prefs.timeZone); await props.saveWorkspace({ preferences: preferencesSchema.parse(prefs) }); setMessage('Preferences saved'); } catch (e: any) { setMessage(e.message); } }}><Field label="Appearance"><select value={prefs.theme} onChange={e => setPrefs({ ...prefs, theme: e.target.value as any })}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></Field><Field label="Time zone"><input value={prefs.timeZone} onChange={e => setPrefs({ ...prefs, timeZone: e.target.value })}/><small>Existing item schedules retain their saved time zone.</small></Field><Field label="Units preference"><select value={prefs.units} onChange={e => setPrefs({ ...prefs, units: e.target.value as any })}><option>SI</option><option>US</option></select><small>Original lab units are always retained.</small></Field><label className="checkbox"><input type="checkbox" checked={prefs.healthEnabled} onChange={e => setPrefs({ ...prefs, healthEnabled: e.target.checked })}/> Show Health</label><label className="checkbox"><input type="checkbox" checked={prefs.reminderNames} onChange={e => setPrefs({ ...prefs, reminderNames: e.target.checked })}/> Include item names in reminders</label><button>Save preferences</button><p role="status" className="muted">{message}</p></form>
    <section><h3>Reminders</h3><p className="muted">Optional browser notifications. Delivery depends on your browser and connection.</p><button onClick={async () => { try { const cfg = await api('/api/config'); if (!cfg.push) throw new Error('Push is not configured on this server'); if (!('serviceWorker' in navigator) || !('PushManager' in window)) throw new Error('Push is unavailable in this browser'); await navigator.serviceWorker.register('/sw.js'); const reg = await navigator.serviceWorker.ready; const status = await Notification.requestPermission(); if (status !== 'granted') throw new Error('Notification permission was not granted'); const sub = await reg.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: cfg.vapidPublicKey }); await post('/push', sub.toJSON()); await props.saveWorkspace({ preferences: { ...prefs, remindersEnabled: true } }); setMessage('Reminders enabled'); } catch (e: any) { setMessage(e.message); } }}>Enable reminders</button></section>
    <ImportPanel {...props}/><section><h3>Data & access</h3><div className="row wrap"><button onClick={async () => { try { download('cycletracker-export.json', await api('/export')); } catch (e: any) { setMessage(e.message); } }}><Download size={16}/> Export my data</button><button onClick={async () => { try { setSessions(await api('/sessions')); } catch (e: any) { setMessage(e.message); } }}>View sessions</button></div>{sessions.map(s => <div className="list-row" key={s.id}><span>{s.userAgent || 'Device session'}<small>Expires {formatDate(s.expiresAt)}</small></span><button onClick={async () => { await post('/api/auth/revoke-session', { token: s.token }); setSessions(old => old.filter(x => x.id !== s.id)); }}>Revoke</button></div>)}<p className="muted small">PDF attachments download separately. Health data is retained until you delete it or delete your account; encrypted backups expire after 30 days under the deployment policy.</p></section>
    <button onClick={props.signOut}><LogOut size={16}/> Sign out & clear this device</button><details><summary>Delete account</summary><p>Deletes your records, attachments and sessions. This cannot be undone.</p><button className="danger" onClick={async () => { if (prompt('Type DELETE to permanently delete your account') !== 'DELETE') return; try { await post('/account', { confirmation: 'DELETE' }, 'DELETE'); await local.cache.where('owner').equals(props.user.id).delete(); await local.queue.where('owner').equals(props.user.id).delete(); localStorage.removeItem('cycletracker-active-user'); location.reload(); } catch (e: any) { setMessage(e.message); } }}>Permanently delete account</button></details>
  </div>;
}
