import { useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { entrySchema, occurrences, type Entry, type Unit } from '../../../packages/domain/src/index.js';
import { catalog } from '../../../packages/domain/src/catalog.js';
import { Field } from './ui.js';
const id = () => crypto.randomUUID();
export function EntryEditor({ value, timeZone, onSave }: { value?: Entry; timeZone: string; onSave(e: Entry): Promise<void> }) {
  const [draft, setDraft] = useState<any>(value ?? { id: id(), version: 1, name: '', compoundId: '', formulationId: '', route: 'Oral', enabled: true, amount: { value: '', unit: 'mg' }, notes: '', schedule: { kind: 'daily', timeZone, startDate: new Date().toLocaleDateString('en-CA'), weekdays: [1, 3, 5], intervalDays: 2, intervalHours: 48, slots: [{ id: id(), time: '08:00', amount: { value: '', unit: 'mg' } }] } });
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const change = (key: string, v: any) => setDraft({ ...draft, [key]: v });
  const schedule = (key: string, v: any) => change('schedule', { ...draft.schedule, [key]: v });
  const unit = draft.amount.unit as Unit;
  const select = (key: string) => { const c = catalog.find(x => x.id === key); if (c) setDraft({ ...draft, formulationId: c.id, compoundId: c.compoundId, name: c.name, route: c.route }); else setDraft({ ...draft, formulationId: id(), compoundId: id(), name: '', route: 'Oral' }); };
  const parsed = entrySchema.safeParse(draft);
  let preview = ''; if (parsed.success && draft.schedule.kind !== 'prn') { try { const from = new Date().toISOString(); const end = new Date(Date.now() + 7 * 864e5).toISOString(); const events = occurrences({ id: 'preview', name: 'Preview', category: 'Custom', notes: '', archived: false, entries: [parsed.data] }, from, end); preview = `${events.length} administrations in the next 7 days · ${events.reduce((sum, e) => sum + e.amount.value, 0)} ${unit} total${events.some(e => e.adjusted) ? ' · daylight-saving adjustment applies' : ''}`; } catch (e) { preview = String(e); } }
  return <form onSubmit={async e => { e.preventDefault(); setError(''); setBusy(true); try { await onSave(entrySchema.parse(draft)); } catch (err: any) { setError(err.issues?.map((x: any) => x.message).join('; ') ?? err.message); } finally { setBusy(false); } }}>
    {!value && <Field label="Choose a formulation"><select defaultValue="" onChange={e => select(e.target.value)}><option value="">Custom medication or supplement</option>{catalog.map(c => <option key={c.id} value={c.id}>{c.name} · {c.route}</option>)}</select></Field>}
    <Field label="Item name"><input required value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value, compoundId: draft.compoundId || id(), formulationId: draft.formulationId || id() })} placeholder="e.g. My supplement"/></Field>
    <div className="grid two"><Field label="Route"><select value={draft.route} onChange={e => change('route', e.target.value)}>{['Oral', 'Intramuscular oil', 'Intramuscular aqueous', 'Intramuscular', 'Subcutaneous', 'Transdermal', 'Other'].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Amount unit"><select value={unit} onChange={e => setDraft({ ...draft, amount: { ...draft.amount, unit: e.target.value }, schedule: { ...draft.schedule, slots: draft.schedule.slots.map((s: any) => ({ ...s, amount: { ...s.amount, unit: e.target.value } })) } })}>{['mg', 'mcg', 'g', 'IU', 'mL'].map(u => <option key={u}>{u}</option>)}</select></Field></div>
    <Field label="Schedule"><select value={draft.schedule.kind} onChange={e => schedule('kind', e.target.value)}><option value="daily">Every day</option><option value="weekdays">Selected weekdays</option><option value="interval">Every N calendar days</option><option value="elapsed">Every N elapsed hours</option><option value="prn">As needed</option></select></Field>
    <div className="grid two"><Field label="Start date / interval anchor"><input type="date" required value={draft.schedule.startDate} onChange={e => schedule('startDate', e.target.value)}/></Field><Field label="End date (optional)"><input type="date" value={draft.schedule.endDate ?? ''} onChange={e => schedule('endDate', e.target.value || undefined)}/></Field></div>
    <Field label="Schedule time zone"><input required value={draft.schedule.timeZone} onChange={e => schedule('timeZone', e.target.value)}/></Field>
    {draft.schedule.kind === 'weekdays' && <div className="weekdays">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((d, i) => <button type="button" className={draft.schedule.weekdays.includes(i + 1) ? 'selected' : ''} key={d} onClick={() => schedule('weekdays', draft.schedule.weekdays.includes(i + 1) ? draft.schedule.weekdays.filter((n: number) => n !== i + 1) : [...draft.schedule.weekdays, i + 1])}>{d}</button>)}</div>}
    {draft.schedule.kind === 'interval' && <Field label="Repeat every N days"><input type="number" min="1" value={draft.schedule.intervalDays} onChange={e => schedule('intervalDays', +e.target.value)}/></Field>}
    {draft.schedule.kind === 'elapsed' && <><Field label="Hours between administrations"><input type="number" min="1" value={draft.schedule.intervalHours} onChange={e => schedule('intervalHours', +e.target.value)}/></Field><Field label="Exact anchor (ISO timestamp with offset)"><input placeholder="2026-09-09T08:00:00+02:00" value={draft.schedule.anchorInstant ?? ''} onChange={e => schedule('anchorInstant', e.target.value)}/></Field></>}
    {draft.schedule.slots.map((slot: any, i: number) => <div className="row" key={slot.id}><Field label={draft.schedule.kind === 'prn' ? 'Suggested time (not due)' : 'Local time'}><input type="time" required value={slot.time} onChange={e => schedule('slots', draft.schedule.slots.map((s: any, n: number) => n === i ? { ...s, time: e.target.value } : s))}/></Field><Field label={`Amount per administration (${unit})`}><input type="number" step="any" min="0.000001" required value={slot.amount.value} onChange={e => setDraft({ ...draft, amount: i === 0 ? { value: +e.target.value, unit } : draft.amount, schedule: { ...draft.schedule, slots: draft.schedule.slots.map((s: any, n: number) => n === i ? { ...s, amount: { value: +e.target.value, unit } } : s) } })}/></Field>{i > 0 && <button type="button" className="icon-button" aria-label="Remove time" onClick={() => schedule('slots', draft.schedule.slots.filter((_: any, n: number) => n !== i))}><Trash2 size={16}/></button>}</div>)}
    {!['elapsed', 'prn'].includes(draft.schedule.kind) && <button type="button" className="text-button" onClick={() => schedule('slots', [...draft.schedule.slots, { id: id(), time: '20:00', amount: { value: '', unit } }])}><Plus size={16}/> Add another time</button>}
    <details><summary>Formulation, package & notes</summary><div className="grid two"><Field label={`Concentration (${unit === 'mL' ? 'mg' : unit}/mL)`}><input type="number" min="0" step="any" value={draft.concentration?.value ?? ''} onChange={e => change('concentration', e.target.value ? { value: +e.target.value, unit: unit === 'mL' ? 'mg' : unit } : undefined)}/></Field><Field label={`Pill strength (${unit}/pill)`}><input type="number" min="0" step="any" value={draft.pillStrength?.value ?? ''} onChange={e => change('pillStrength', e.target.value ? { value: +e.target.value, unit } : undefined)}/></Field></div><Field label={`Total amount per package (${unit})`}><input type="number" min="0" step="any" value={draft.packageAmount?.value ?? ''} onChange={e => change('packageAmount', e.target.value ? { value: +e.target.value, unit } : undefined)}/></Field><Field label="Notes"><textarea value={draft.notes} onChange={e => change('notes', e.target.value)}/></Field></details>
    {preview && <div className="notice">{preview}</div>}{error && <p role="alert" className="error">{error}</p>}<button className="primary full" disabled={busy}>{busy ? 'Saving…' : 'Save item'}</button>
  </form>;
}
