import { useRef, useState } from 'react';
import type { Shared } from './App.js';
import type { ImportPreview } from '../../../packages/domain/src/import.js';
import { administrationSchema, type Entry } from '../../../packages/domain/src/index.js';
import { post, download } from './api.js';
import { Field, Sheet } from './ui.js';
export function ImportPanel(props: Shared) { const request = useRef<any>(null);
  const [preview, setPreview] = useState<ImportPreview | null>(null); const [original, setOriginal] = useState<unknown>(); const [error, setError] = useState(''); const [includePhases, setIncludePhases] = useState(false); const [busy, setBusy] = useState(false); const [mapping, setMapping] = useState<ImportPreview['unresolved'][number] | null>(null);
  const entries = props.ws.protocol.phases.flatMap(p => p.entries);
  return <section><h3>Import records</h3><Field label="Cycle Dashboard or CycleTracker JSON export"><input type="file" accept="application/json,.json" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; try { if (file.size > 4e6) throw new Error('Split exports larger than 4 MB before importing'); const raw = JSON.parse(await file.text()); const result = await post<ImportPreview>('/import/preview', raw); request.current = null; setIncludePhases(false); setOriginal(raw); setPreview(result); setError(''); } catch (err: any) { setError(err.message); } }}/></Field>{error && <p className="error">{error}</p>}
    <Sheet open={!!preview} onClose={() => setPreview(null)} title="Import preview" description="Review the mappings before adding records to this account.">{preview && <><p>{preview.records.length} mapped · {preview.records.filter(r => r.duplicate).length} duplicates · {preview.unresolved.length} unresolved</p><p className="muted small">Destination: {props.user.email}</p>{preview.warnings.map(w => <p className="muted small" key={w}>{w}</p>)}<button onClick={() => download('source-export-backup.json', original)}>Download source backup</button><div className="import-list">{preview.records.map(r => <div className="list-row" key={r.sourceId}><strong>{r.data.snapshot?.name ?? r.data.title}</strong><span>{r.data.at} · {r.duplicate ? 'Already imported' : 'Ready to import'}</span></div>)}{preview.unresolved.map(r => <div className="list-row" key={r.sourceId}><strong>{r.sourceId}</strong><span>{r.reason}</span><details><summary>Original record</summary><pre className="source-record">{JSON.stringify(r.raw, null, 2)}</pre></details>{r.canMapAdministration && <button onClick={() => setMapping(r)} disabled={!entries.length || busy || !!request.current}>Map to a routine item</button>}</div>)}</div>{!entries.length && preview.unresolved.some(r => r.canMapAdministration) && <p className="muted small">Create matching items in Plan before mapping legacy administrations.</p>}{preview.duplicatePhases > 0 && <p>{preview.duplicatePhases} phases already imported</p>}{!!preview.protocol?.phases.length && <label className="checkbox"><input type="checkbox" disabled={busy || !!request.current} checked={includePhases} onChange={e => setIncludePhases(e.target.checked)}/> Add {preview.protocol.phases.length} phases as drafts</label>}{preview.documents.length > 0 && <p className="muted small">{preview.documents.length} attachment references. Upload available PDFs separately in Health.</p>}{error && <p className="error">{error}</p>}<button className="primary full" disabled={busy || (!preview.records.some(r => !r.duplicate) && !includePhases)} onClick={async () => { setBusy(true); try { request.current ??= { operationId: crypto.randomUUID(), confirmed: true, expectedVersion: props.ws.version, records: preview.records.filter(r => !r.duplicate), protocolSourceId: preview.protocolSourceId, protocol: includePhases ? preview.protocol : null }; const result = await post('/import/apply', request.current); await props.reload(); setPreview(null); props.setToast(`Imported ${result.imported} records; ${result.duplicates} duplicates skipped${result.drafts ? `; ${result.drafts} draft phases added` : ""}${result.duplicatePhases ? `; ${result.duplicatePhases} phases already imported` : ""}`); } catch (err: any) { setError(err.message); } finally { setBusy(false); } }}>{busy ? 'Importing…' : 'Import reviewed records'}</button></>}</Sheet>
    <Sheet open={!!mapping} onClose={() => setMapping(null)} title="Map legacy administration" description="Use the recorded value from the source. Leave uncertain amounts unresolved.">{mapping && <LegacyMapping row={mapping} entries={entries} save={data => { setPreview(old => old ? { ...old, records: [...old.records, { sourceId: mapping.sourceId, kind: 'administration', duplicate: false, data }], unresolved: old.unresolved.filter(r => r.sourceId !== mapping.sourceId) } : old); setMapping(null); }}/>}</Sheet>
  </section>;
}
function LegacyMapping({ row, entries, save }: { row: ImportPreview['unresolved'][number]; entries: Entry[]; save(data: unknown): void }) {
  const [entryId, setEntryId] = useState(entries[0]?.id); const [error, setError] = useState(''); const entry = entries.find(e => e.id === entryId);
  return <form onSubmit={e => { e.preventDefault(); const f = Object.fromEntries(new FormData(e.currentTarget)); try { if (!entry) throw new Error('Choose an item'); save(administrationSchema.parse({ occurrenceId: null, phaseId: null, entryId: null, snapshot: entry, importSource: { sourceId: row.sourceId, format: 'cycle-dashboard', raw: row.raw }, at: f.timestamp, status: 'taken', amount: { value: Number(f.amount), unit: f.unit }, note: f.note })); } catch (err: any) { setError(err.message); } }}><details><summary>Original record</summary><pre className="source-record">{JSON.stringify(row.raw, null, 2)}</pre></details><Field label="Formulation"><select value={entryId} onChange={e => setEntryId(e.target.value)}>{entries.map(e => <option key={e.id} value={e.id}>{e.name} · {e.route}</option>)}</select></Field><Field label="Original timestamp (ISO with offset)"><input name="timestamp" required defaultValue={(row.raw as any)?.created_at ?? (row.raw as any)?.ts ?? (row.raw as any)?.at ?? ''}/></Field><div className="grid two"><Field label="Recorded amount"><input name="amount" type="number" step="any" min="0.000001" required/></Field><Field label="Recorded unit"><select name="unit" defaultValue={entry?.amount.unit}>{['mg', 'mcg', 'g', 'IU', 'mL'].map(u => <option key={u}>{u}</option>)}</select></Field></div><Field label="Original note"><textarea name="note" defaultValue={(row.raw as any)?.data?.notes ?? (row.raw as any)?.notes ?? ""}/></Field>{error && <p className="error">{error}</p>}<button className="primary full">Use this mapping</button></form>;
}
