import { useEffect, useRef, useState } from 'react';
import * as echarts from 'echarts/core';
import { LineChart, ScatterChart } from 'echarts/charts';
import { GridComponent, TooltipComponent, LegendComponent, DataZoomComponent, MarkLineComponent } from 'echarts/components';
import { CanvasRenderer } from 'echarts/renderers';
echarts.use([LineChart, ScatterChart, GridComponent, TooltipComponent, LegendComponent, DataZoomComponent, MarkLineComponent, CanvasRenderer]);
import { Copy, Download, Plus, SlidersHorizontal, Trash2 } from 'lucide-react';
import { catalog, CATALOG_VERSION } from '../../../packages/domain/src/catalog.js';
import { convert, occurrences, entrySchema, type Entry } from '../../../packages/domain/src/index.js';
import { scenarioSchema, type Scenario, type Simulation } from '../../../packages/simulation/src/index.js';
import type { Shared } from './App.js';
import { api, download, type SavedRecord } from './api.js';
import { Empty, Field, Sheet } from './ui.js';
type LocalScenario = { id: string; scenario: Scenario; saved?: SavedRecord; visible: boolean };
const colors = ['#0d8a7b', '#6976d7', '#d68f38', '#b35e95'];
export default function Plotter(props: Shared) {
  const [scenarios, setScenarios] = useState<LocalScenario[]>([]); const [editing, setEditing] = useState<LocalScenario | 'new' | null>(null);
  const [from, setFrom] = useState(new Date().toISOString().slice(0, 10)); const [to, setTo] = useState(new Date(Date.now() + 42 * 864e5).toISOString().slice(0, 10));
  const [results, setResults] = useState<Simulation[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [duration, setDuration] = useState(0);
  const chartDiv = useRef<HTMLDivElement>(null); const chart = useRef<echarts.ECharts | null>(null);
  const visible = scenarios.filter(s => s.visible);
  useEffect(() => {
    if (!visible.length) { setResults([]); return; }
    setBusy(true); setError(''); const worker = new Worker(new URL('./simulation.worker.ts', import.meta.url), { type: 'module' });
    worker.onmessage = e => { setBusy(false); if (e.data.error) { setError(e.data.error); setResults([]); } else { setResults(e.data.results); setDuration(e.data.duration); } };
    worker.onerror = () => { setBusy(false); setError('Simulation worker failed. Edit the scenario to retry.'); };
    worker.postMessage({ scenarios: visible.map(s => s.scenario), from: `${from}T00:00:00Z`, to: `${to}T00:00:00Z` });
    return () => worker.terminate();
  }, [scenarios, from, to]);
  useEffect(() => {
    if (!chartDiv.current) return;
    const instance = echarts.init(chartDiv.current); chart.current = instance; const observer = new ResizeObserver(() => instance.resize()); observer.observe(chartDiv.current);
    return () => { observer.disconnect(); instance.dispose(); chart.current = null; };
  }, []);
  useEffect(() => {
    chart.current?.setOption({ animation: false, color: visible.map(s => s.scenario.color), textStyle: { fontFamily: 'Inter, system-ui, sans-serif' }, grid: { left: 68, right: 22, top: 45, bottom: 75 }, tooltip: { trigger: 'axis', valueFormatter: (v: any) => Number(v).toFixed(2) }, legend: { show: false }, xAxis: { type: 'time', axisLine: { lineStyle: { color: '#9daea8' } }, splitLine: { show: false } }, yAxis: { type: 'value', name: '% reference-dose peak', nameLocation: 'end', nameTextStyle: { align: 'left' }, splitLine: { lineStyle: { color: '#dce5e0', type: 'dashed' } } }, dataZoom: [{ type: 'inside' }, { type: 'slider', height: 20, bottom: 15 }], series: results.flatMap(r => {
      const present = Date.now(); const common = { type: 'line', showSymbol: false, symbolSize: 5, connectNulls: false, color: r.scenario.color, emphasis: { focus: 'series' }, lineStyle: { width: 2.5 } };
      const historical = r.points.filter(p => p[0] <= present); const projected = r.points.filter(p => p[0] >= present);
      return [{ ...common, name: r.scenario.name, data: r.scenario.mode === 'planned' ? [] : historical, markLine: { silent: true, symbol: 'none', lineStyle: { color: '#95a59f', type: 'dashed' }, data: [{ xAxis: present, label: { formatter: 'Now' } }] } }, { ...common, name: `${r.scenario.name} · ${r.scenario.mode === 'recorded' ? 'residual estimate' : 'planned'}`, data: r.scenario.mode === 'planned' ? r.points : projected, lineStyle: { width: 2.5, type: 'dashed' } }, { type: 'scatter', name: `${r.scenario.name} doses`, color: r.scenario.color, symbol: 'triangle', symbolSize: 6, data: r.scenario.events.filter(e => Date.parse(e.at) >= Date.parse(r.from) && Date.parse(e.at) <= Date.parse(r.to)).map(e => [Date.parse(e.at), 0]) }]; }) }, true);
  }, [results]);
  const saved = props.records.filter(r => r.kind === 'scenario');
  return <><div className="page-heading"><div><h1>Plotter</h1></div><button className="primary" onClick={() => setEditing('new')}><Plus size={17}/> Add scenario</button></div>
    <div className="plot-layout"><aside className="panel scenario-panel"><div className="row spread"><h2>Scenarios</h2><span className="badge">{scenarios.length}</span></div><p className="muted small">Scenario edits do not change your routine.</p>{!scenarios.length && <p className="muted">Choose a formulation, amount and schedule.</p>}{scenarios.map(s => <div className="scenario-card" key={s.id} style={{ borderLeftColor: s.scenario.color }}><div className="row spread"><label className="checkbox"><input type="checkbox" checked={s.visible} onChange={e => setScenarios(old => old.map(x => x.id === s.id ? { ...x, visible: e.target.checked } : x))}/><strong>{s.scenario.name}</strong></label><button className="icon-button" aria-label={`Remove ${s.scenario.name}`} onClick={() => setScenarios(old => old.filter(x => x.id !== s.id))}><Trash2 size={15}/></button></div><small>{s.scenario.events.length} dose events · {s.scenario.mode}</small><small>Reference: {s.scenario.model.scale.kind === 'relative' ? `${s.scenario.model.scale.referenceDose} mg single-dose peak` : 'absolute'}</small><div className="row wrap"><button className="text-button" onClick={() => setEditing(s)}><SlidersHorizontal size={14}/> Edit</button><button className="icon-button" aria-label={`Duplicate ${s.scenario.name}`} onClick={() => setScenarios(old => [...old, { id: crypto.randomUUID(), scenario: { ...structuredClone(s.scenario), name: s.scenario.name + ' copy', color: colors[old.length % colors.length] }, visible: true }])}><Copy size={14}/></button><button className="text-button" onClick={async () => { try { const result = await props.saveRecord('scenario', s.scenario, s.saved); setScenarios(old => old.map(x => x.id === s.id ? { ...x, saved: result } : x)); } catch (e: any) { setError(e.message); } }}>Save</button></div><details><summary>Model and sources</summary><p>{s.scenario.model.source}</p><p className="small">{catalog.find(c => c.id === s.scenario.formulationId)?.limitations ?? 'User-entered exploratory parameters. Not independently validated.'}</p>{catalog.find(c => c.id === s.scenario.formulationId)?.sources.map(source => <a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.locator} ↗</a>)}</details></div>)}<button className="full" onClick={() => setEditing('new')}><Plus size={16}/> Add comparison</button>{saved.length > 0 && <details><summary>Saved scenarios</summary>{saved.map(r => <button key={r.id} onClick={() => setScenarios(old => [...old, { id: crypto.randomUUID(), scenario: r.data, saved: r, visible: true }])}>{r.data.name}</button>)}</details>}</aside>
    <section className="panel plot-panel"><div className="plot-toolbar"><div><h2>Modeled exposure</h2><span className="badge">Relative curves · Research preview</span></div><div className="row wrap"><Field label="From (UTC)"><input type="date" value={from} onChange={e => setFrom(e.target.value)}/></Field><Field label="To (UTC)"><input type="date" value={to} onChange={e => setTo(e.target.value)}/></Field></div></div><div className="chart-wrap"><div ref={chartDiv} className="chart" role="img" aria-label="Interactive exposure chart; exact values and metrics are available below"/>{!scenarios.length && <div className="chart-empty"><Empty title="No scenarios">Add a scenario to plot exposure.</Empty></div>}{busy && <span className="chart-busy" role="status">Calculating…</span>}</div>{error && <p className="error" role="alert">{error}</p>}<div className="plot-caption"><span><i className="solid-line"/> Recorded-dose estimates</span><span><i className="dashed-line"/> Planned / future estimates</span><span>△ Administration</span></div><div className="notice">Relative exposure is not a measured blood concentration or potency comparison. The reference denominator stays fixed when you zoom.</div><div className="row wrap"><button disabled={!results.length} onClick={() => download('cycletracker-scenarios.json', { results, exportedAt: new Date().toISOString() })}><Download size={15}/> JSON</button><button disabled={!results.length} onClick={() => download('cycletracker-curves.csv', 'scenario,timestamp,value,unit\n' + results.flatMap(r => r.points.map(p => [JSON.stringify(r.scenario.name), new Date(p[0]).toISOString(), p[1], JSON.stringify(r.unit)].join(','))).join('\n'), 'text/csv')}><Download size={15}/> CSV</button><button disabled={!results.length} onClick={() => { if (!chart.current) return; const a = document.createElement('a'); a.href = chart.current.getDataURL({ type: 'png', pixelRatio: 2, backgroundColor: '#fff' }); a.download = 'cycletracker-chart.png'; a.click(); }}>Chart image</button><button disabled={!results.length} onClick={() => window.print()}>Print report</button><small className="muted">{duration ? `${duration.toFixed(0)} ms · complete input events · engine bateman-1.0.0` : ''}</small></div></section></div>
    {results.length > 0 && <section className="panel"><h2>Within the selected interval</h2><p className="muted">{from} through {to} UTC. Metrics use the full interval, not the zoomed view.</p><div className="table-scroll"><table><thead><tr><th>Scenario</th><th>Peak</th><th>Trough</th><th>Average</th><th>AUC (%·h)</th><th>Fluctuation</th></tr></thead><tbody>{results.map((r, i) => <tr key={i}><td>{r.scenario.name}</td><td>{r.metrics.peak.toFixed(2)}</td><td>{r.metrics.trough.toFixed(2)}</td><td>{r.metrics.average.toFixed(2)}</td><td>{r.metrics.auc.toFixed(2)}</td><td>{r.metrics.fluctuation === null ? '—' : `${(r.metrics.fluctuation * 100).toFixed(1)}%`}</td></tr>)}</tbody></table></div><p className="muted small">Steady state is not inferred for finite or irregular scenarios. Absolute serum display and lab calibration remain unavailable until formulation-specific validation supports them.</p></section>}
    <Sheet title={editing === 'new' ? 'Add scenario' : 'Edit scenario'} open={!!editing} onClose={() => setEditing(null)} description="Scenario edits do not change your routine or recorded doses.">{editing && <ScenarioEditor key={editing === 'new' ? 'new' : editing.id} {...props} initial={editing === 'new' ? undefined : editing} color={colors[scenarios.length % colors.length]} onSave={s => { setScenarios(old => editing === 'new' ? [...old, { id: crypto.randomUUID(), scenario: s, visible: true }] : old.map(x => x.id === editing.id ? { ...x, scenario: s } : x)); setEditing(null); }}/>}</Sheet>
  </>;
}
function ScenarioEditor(props: Shared & { initial?: LocalScenario; color: string; onSave(s: Scenario): void }) {
  const existing = props.initial?.scenario; const [formulation, setFormulation] = useState(existing?.formulationId ?? catalog[0].id); const item = catalog.find(c => c.id === formulation);
  const [mode, setMode] = useState<Scenario['mode']>(existing?.mode ?? 'planned'); const [source, setSource] = useState('manual'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [keepEvents, setKeepEvents] = useState(!!existing); const [manual, setManual] = useState(!item?.model || existing?.model.source.startsWith('User-entered'));
  return <form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); const f = Object.fromEntries(new FormData(e.currentTarget)); try {
    const model = manual ? { ka: Math.log(2) / Number(f.absorption), ke: Math.log(2) / Number(f.elimination), fraction: 1, scale: { kind: 'relative' as const, referenceDose: Number(f.reference) }, parameterVersion: `custom-${new Date().toISOString()}`, source: `User-entered exploratory parameters: ${f.evidence}` } : { ...item!.model!, scale: { kind: 'relative' as const, referenceDose: Number(f.reference) } };
    let events: Scenario['events'] = keepEvents && existing ? existing.events : [];
    if (!keepEvents) {
      if (mode !== 'planned') {
        let cursor: string | null = null; let count = 0;
        do { const response: { items: SavedRecord[]; nextCursor: string | null } = await api(`/records?kind=administration&limit=100${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ''}`); cursor = response.nextCursor;
          for (const r of response.items) if (r.data.status === 'taken' && r.data.snapshot.formulationId === formulation) events.push({ at: r.data.at, doseMg: convert(r.data.amount, 'mg', r.data.snapshot.concentration), origin: 'recorded' });
          count += response.items.length; if (count > 100000) throw new Error('History exceeds the current scenario limit');
        } while (cursor);
      }
      if (mode !== 'recorded' && f.continue !== 'stop') {
        const active = props.ws.protocol.phases.find(p => p.id === props.ws.protocol.activePhaseId);
        const start = new Date(`${f.start}T00:00:00Z`).toISOString(); const end = new Date(`${f.end}T00:00:00Z`).toISOString();
        let entry: Entry;
        if (source === 'active') { const configured = active?.entries.find(x => x.formulationId === formulation); if (!configured) throw new Error('This formulation is not in the active routine'); entry = configured; }
        else entry = entrySchema.parse({ id: 'scenario', version: 1, compoundId: item?.compoundId ?? formulation, formulationId: formulation, name: item?.name ?? 'Custom', route: item?.route ?? 'Other', amount: { value: Number(f.dose), unit: 'mg' }, schedule: { kind: 'interval', timeZone: props.ws.preferences.timeZone, startDate: f.start, endDate: f.end, intervalDays: Number(f.interval), slots: [{ id: 's', time: f.time, amount: { value: Number(f.dose), unit: 'mg' } }] } });
        for (const o of occurrences({ id: 'scenario', name: 'Scenario', category: 'Custom', archived: false, notes: '', entries: [entry] }, start, end)) if (mode === 'planned' || Date.parse(o.at) > Date.now()) events.push({ at: o.at, doseMg: convert(o.amount, 'mg', o.entry.concentration), origin: 'planned' });
      }
    }
    if (!events.length) throw new Error('No eligible dose events. Enter a schedule or record matching administrations.');
    props.onSave(scenarioSchema.parse({ name: f.name, color: existing?.color ?? props.color, formulationId: formulation, analyte: item?.analyte ?? formulation, model, events, catalogVersion: CATALOG_VERSION, mode }));
  } catch (err: any) { setError(err.issues?.map((x: any) => x.message).join('; ') ?? err.message); } finally { setBusy(false); } }}>
    <Field label="Scenario name"><input name="name" defaultValue={existing?.name ?? ''} required placeholder="e.g. A schedule to compare"/></Field><Field label="Compound / formulation"><select value={formulation} onChange={e => { setFormulation(e.target.value); setManual(!catalog.find(c => c.id === e.target.value)?.model); setKeepEvents(false); }}>{catalog.map(c => <option key={c.id} value={c.id}>{c.name} · {c.capability === 'tracking-only' ? 'no default model' : 'relative model'}</option>)}</select></Field>
    <Field label="Dose inputs"><select value={mode} onChange={e => { setMode(e.target.value as any); setKeepEvents(false); }}><option value="planned">Planned scenario</option><option value="recorded">Recorded administrations only</option><option value="combined">Recorded history + explicit future plan</option></select></Field>
    {existing && <label className="checkbox"><input type="checkbox" checked={keepEvents} onChange={e => setKeepEvents(e.target.checked)}/> Keep these {existing.events.length} exact event inputs</label>}
    {!keepEvents && mode !== 'recorded' && <><Field label="Schedule source"><select value={source} onChange={e => setSource(e.target.value)}><option value="manual">Enter a sandbox schedule</option><option value="active">Copy matching active-routine item</option></select></Field><div className="grid two"><Field label="Start date"><input type="date" name="start" required defaultValue={new Date().toISOString().slice(0, 10)}/></Field><Field label="End date (exclusive)"><input type="date" name="end" required defaultValue={new Date(Date.now() + 42 * 864e5).toISOString().slice(0, 10)}/></Field></div>{source === 'manual' && <><div className="grid two"><Field label="Amount per administration (mg)"><input name="dose" type="number" step="any" min="0.000001" required/></Field><Field label="Every N calendar days"><input name="interval" type="number" min="1" defaultValue="1" required/></Field></div><Field label={`Administration time (${props.ws.preferences.timeZone})`}><input name="time" type="time" defaultValue="08:00" required/></Field></>}<Field label="Future administrations"><select name="continue"><option value="continue">Continue this schedule</option><option value="stop">Stop future administrations (history only)</option></select></Field></>}
    <Field label="Fixed normalization reference dose (mg)"><input name="reference" type="number" min="0.000001" step="any" defaultValue={existing?.model.scale.kind === 'relative' ? existing.model.scale.referenceDose : ''} required/><small>100% is this formulation's modeled single-dose peak at this amount. It does not change when zooming.</small></Field>
    <label className="checkbox"><input type="checkbox" checked={manual} disabled={!item?.model} onChange={e => setManual(e.target.checked)}/> Enter exploratory parameters</label>{manual && <><div className="notice">These inputs are your explicit assumptions. No absolute blood concentration is inferred. IU-based formulations require a separate supported mass basis; do not substitute syringe markings.</div><div className="grid two"><Field label="Absorption half-life (hours)"><input name="absorption" type="number" step="any" min="0.000001" required defaultValue={existing ? Math.log(2) / existing.model.ka : ''}/></Field><Field label="Elimination half-life (hours)"><input name="elimination" type="number" step="any" min="0.000001" required defaultValue={existing ? Math.log(2) / existing.model.ke : ''}/></Field></div><Field label="Source / assumption notes"><textarea name="evidence" required defaultValue={existing?.model.source}/></Field></>}
    <p className="muted small">{item?.limitations}</p>{error && <p className="error" role="alert">{error}</p>}<button className="primary full" disabled={busy}>{busy ? 'Preparing complete history…' : 'Plot scenario'}</button>
  </form>;
}
